### PR TITLE
WIP: start of notebook building machinery

### PR DESCRIPTION
**Pull request by matthew-brett**
Try with `make notebooks`

Comments welcome.  I'll update over the next few days.

### CODE REVIEW

**Comment by matthew-brett** [comment]
The built markdown doesn't seem to render right:

```
# May error after one or a few notebooks, but nevermind
make notebooks
make html
```

Then open `build/html/examples/Atoms.html` - the LaTeX isn't rendering right for me.  Anyone else get this?

**Comment by jonathan-taylor** [comment]
Same issue for me with rendered latex

**Comment by Carreau** [comment]
@willingc, you grand sphinx/notebook/documentation master, do you have any insight on how to have sphinx recognize mathjax in markdown ?

**Comment by willingc** [comment]
@Carreau Quick answer now but can dig in more in a few hours. I would try using recommonmark as in this [repo]. You may need to pin it to the version in the environment.yml.

**Comment by matthew-brett** [comment]
Superseded by #35.

**Pull request closed without merging**
